# baseURL = "https://ergol.org"
relativeURLs = false  # our 404 page does not support relative URLs
locale = "fr"
title = "Ergo‑L"

[params]
subtitle = "Disposition clavier ergonomique pour le français, l’anglais et le code."
description = "Une disposition de clavier ergonomique de type Colemak, optimisée pour le français, l’anglais et le code."

[security]
allowContent = ['text/html', 'text/markdown']
[security.exec]
allow = ["pandoc"]

[markup]
defaultMarkdownHandler = "pandoc"

[taxonomies]
tag = "tags"
author = "authors"
# category = "categories"

[module]
    [[module.mounts]]
        source = "../code"
        target = "assets/js"
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "../corpus"
        target = "static/corpus"
    [[module.mounts]]
        source = "../keymaps"
        target = "static/keymaps"
    [[module.mounts]]
        source = "static"
        target = "static"

[menus]
    [[menus.main]]
        name    = "Ergo‑L"
        pageRef = "/"
        weight  = 1
    [[menus.main]]
        name    = "Installation"
        pageRef = "/installation"
        weight  = 2
    [[menus.main]]
        name    = "Apprendre"
        pageRef = "/apprendre"
        weight  = 3
    [[menus.main]]
        name    = "Aide"
        pageRef = "/aide"
        weight  = 4
    [[menus.main]]
        name    = "Articles"
        pageRef = "/articles"
        weight  = 5
    [[menus.main]]
        name    = "Glossaire"
        pageRef = "/aide/glossaire"
        parent  = "Aide"
        weight  = 1
    [[menus.main]]
        name    = "FAQ"
        pageRef = "/aide/faq"
        parent  = "Aide"
        weight  = 2
    [[menus.main]]
        name    = "Autre ressources"
        pageRef = "/ressources"
        weight  = 6
    [[menus.main]]
        name    = "Dispositions alternatives"
        pageRef = "/alternatives"
        parent  = "Autre ressources"
        weight  = 1
    [[menus.main]]
        name    = "Analyseur"
        pageRef = "/stats"
        parent  = "Autre ressources"
        weight  = 2
    [[menus.main]]
        name    = "Claviers ergonomiques"
        pageRef = "/claviers"
        parent  = "Autre ressources"
        weight  = 3

# Disable RSS everywhere, and enable it manually in /content/articles/_index.md
[outputs]
    home     = ["html"]
    section  = ["html"]
    taxonomy = ["html"]
    term     = ["html"]

[params.extra.mastodon]
enable = true
host = "eldritch.cafe"
username = "ergonautes"
